/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemacontrole;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author jaime
 */
public class FuncoesWindow extends javax.swing.JFrame {
    public boolean theresError;
    public String erro = "";
    /**
     * Creates new form FuncoesWindow
     */
    public FuncoesWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoFuncao = new javax.swing.ButtonGroup();
        tipoMalha = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        variaveisControleGroup = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        polosGanhosGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FuncaoQuadrada = new javax.swing.JRadioButton();
        FuncaoDenteSerra = new javax.swing.JRadioButton();
        FuncaoDegrau = new javax.swing.JRadioButton();
        FuncaoAleatoria = new javax.swing.JRadioButton();
        FuncaoSenoidal = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PeriodoMinimo = new javax.swing.JTextField();
        PeriodoMaximo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        AmplitudeMinima = new javax.swing.JTextField();
        AmplitudeMaxima = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Amplitude = new javax.swing.JTextField();
        Offset = new javax.swing.JTextField();
        Periodo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        CheckMalhaFechada = new javax.swing.JRadioButton();
        CheckMalhaAberta = new javax.swing.JRadioButton();
        tipoControleComboBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        parametrosPIDPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        kpTextField = new javax.swing.JTextField();
        labelKi = new javax.swing.JLabel();
        kiTextField = new javax.swing.JTextField();
        labelKd = new javax.swing.JLabel();
        kdTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        labelTi = new javax.swing.JLabel();
        labelTd = new javax.swing.JLabel();
        tiTextField = new javax.swing.JTextField();
        tdTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        antiWindUpCheckBox = new javax.swing.JCheckBox();
        BotaoGerarFuncao = new javax.swing.JButton();
        filtroDerivativoCheckBox = new javax.swing.JCheckBox();
        pvPanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        pvTanque1 = new javax.swing.JRadioButton();
        pvTanque2 = new javax.swing.JRadioButton();
        parametrosPIDPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        kpTextField1 = new javax.swing.JTextField();
        labelKi1 = new javax.swing.JLabel();
        kiTextField1 = new javax.swing.JTextField();
        labelKd1 = new javax.swing.JLabel();
        kdTextField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        labelTi1 = new javax.swing.JLabel();
        labelTd1 = new javax.swing.JLabel();
        tiTextField1 = new javax.swing.JTextField();
        tdTextField1 = new javax.swing.JTextField();
        jPanelEsquemaControles = new javax.swing.JPanel();
        tipoControleComboBox1 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        radioButtonCascata = new javax.swing.JRadioButton();
        radioButtonSimples = new javax.swing.JRadioButton();
        observadorEstadosRadio = new javax.swing.JRadioButton();
        seguidorRefRadio = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        obsPanel = new javax.swing.JPanel();
        labelObservador = new javax.swing.JLabel();
        radioPolos = new javax.swing.JRadioButton();
        radioGanhos = new javax.swing.JRadioButton();
        inputPolo1 = new javax.swing.JTextField();
        inputPolo2 = new javax.swing.JTextField();
        inputL0 = new javax.swing.JTextField();
        inputL1 = new javax.swing.JTextField();
        L0Label = new javax.swing.JLabel();
        L1Label = new javax.swing.JLabel();
        minusLabel = new javax.swing.JLabel();
        plusLabel = new javax.swing.JLabel();
        polo1Img = new javax.swing.JTextField();
        polo2Img = new javax.swing.JTextField();
        labelSeguidor = new javax.swing.JLabel();
        complxLabel1 = new javax.swing.JLabel();
        complxLabel2 = new javax.swing.JLabel();
        polo3input = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        plusLabel2 = new javax.swing.JLabel();
        polo3Img = new javax.swing.JTextField();
        complxLabel3 = new javax.swing.JLabel();
        ganhoK2input = new javax.swing.JTextField();
        K2Label2 = new javax.swing.JLabel();
        K2Label1 = new javax.swing.JLabel();
        K1Label = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(934, 740));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Tipo de Sinal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 6, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoFuncao.add(FuncaoQuadrada);
        FuncaoQuadrada.setText("Quadrada");
        FuncaoQuadrada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoQuadradaStateChanged(evt);
            }
        });
        jPanel1.add(FuncaoQuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 124, -1, -1));

        TipoFuncao.add(FuncaoDenteSerra);
        FuncaoDenteSerra.setText("Dente de Serra");
        FuncaoDenteSerra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoDenteSerraStateChanged(evt);
            }
        });
        jPanel1.add(FuncaoDenteSerra, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 219, -1, -1));

        TipoFuncao.add(FuncaoDegrau);
        FuncaoDegrau.setText("Degrau");
        FuncaoDegrau.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoDegrauStateChanged(evt);
            }
        });
        jPanel1.add(FuncaoDegrau, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 319, -1, -1));

        TipoFuncao.add(FuncaoAleatoria);
        FuncaoAleatoria.setText("Aleatória");
        FuncaoAleatoria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoAleatoriaStateChanged(evt);
            }
        });
        jPanel1.add(FuncaoAleatoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 410, -1, -1));

        TipoFuncao.add(FuncaoSenoidal);
        FuncaoSenoidal.setSelected(true);
        FuncaoSenoidal.setText("Senoidal");
        FuncaoSenoidal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FuncaoSenoidalStateChanged(evt);
            }
        });
        FuncaoSenoidal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncaoSenoidalActionPerformed(evt);
            }
        });
        jPanel1.add(FuncaoSenoidal, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 37, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/seno.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/quedrada.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 97, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/degrau.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 284, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aleatorio.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 378, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/denteSerra.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 191, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, 270, 460));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel11.setText("Período (s)");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 2, -1, -1));

        jLabel14.setText("Mínimo");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 38, -1, -1));

        jLabel15.setText("Máximo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 38, -1, -1));

        PeriodoMinimo.setText("0");
        jPanel2.add(PeriodoMinimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 59, 50, -1));

        PeriodoMaximo.setText("10");
        PeriodoMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeriodoMaximoActionPerformed(evt);
            }
        });
        jPanel2.add(PeriodoMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 59, 50, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 180, 110));
        this.jPanel2.setVisible(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("Amplitude (V)");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 2, -1, -1));

        AmplitudeMinima.setText("-4");
        jPanel3.add(AmplitudeMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 57, 50, -1));

        AmplitudeMaxima.setText("4");
        AmplitudeMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmplitudeMaximaActionPerformed(evt);
            }
        });
        jPanel3.add(AmplitudeMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 57, 50, -1));

        jLabel12.setText("Mínima");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 36, -1, -1));

        jLabel13.setText("Máxima");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 36, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 274, 179, 100));
        this.jPanel3.setVisible(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setPreferredSize(new java.awt.Dimension(173, 122));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(Amplitude, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 8, 50, -1));
        jPanel4.add(Offset, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 41, 50, -1));
        jPanel4.add(Periodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 74, 50, -1));

        jLabel7.setText("Amplitude:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 14, -1, -1));

        jLabel8.setText("Offset:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 47, -1, -1));

        jLabel9.setText("Período:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 80, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 28, 179, 240));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setText("Parâmetros");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 6, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoMalha.add(CheckMalhaFechada);
        CheckMalhaFechada.setText("Malha Fechada");
        CheckMalhaFechada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckMalhaFechadaStateChanged(evt);
            }
        });
        jPanel5.add(CheckMalhaFechada, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 38, -1, -1));

        tipoMalha.add(CheckMalhaAberta);
        CheckMalhaAberta.setText("Malha Aberta");
        CheckMalhaAberta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckMalhaAbertaStateChanged(evt);
            }
        });
        jPanel5.add(CheckMalhaAberta, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 8, -1, -1));

        tipoControleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "PI", "PD", "PID", "PI-D" }));
        tipoControleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoControleComboBoxActionPerformed(evt);
            }
        });
        this.tipoControleComboBox.setVisible(false);
        jPanel5.add(tipoControleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 89, 123, -1));

        jLabel22.setText("Tipo de Controle");
        this.jLabel22.setVisible(false);
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 68, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 28, 210, 120));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel17.setText("Malha");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 6, -1, -1));

        parametrosPIDPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        parametrosPIDPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Kp");
        parametrosPIDPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 29, -1, -1));

        kpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kpTextFieldKeyTyped(evt);
            }
        });
        parametrosPIDPanel.add(kpTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 23, 77, -1));

        labelKi.setText("Ki");
        this.labelKi.setVisible(false);
        parametrosPIDPanel.add(labelKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 62, -1, -1));

        kiTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kiTextFieldKeyTyped(evt);
            }
        });
        this.kiTextField.setVisible(false);
        parametrosPIDPanel.add(kiTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 56, 77, -1));

        labelKd.setText("Kd");
        this.labelKd.setVisible(false);
        parametrosPIDPanel.add(labelKd, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 95, -1, -1));

        kdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdTextFieldActionPerformed(evt);
            }
        });
        kdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kdTextFieldKeyTyped(evt);
            }
        });
        this.kdTextField.setVisible(false);
        parametrosPIDPanel.add(kdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 89, 78, -1));

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel21.setText("Parâmetros Mestre");
        parametrosPIDPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 2, -1, -1));

        labelTi.setText("Ti");
        this.labelTi.setVisible(false);
        parametrosPIDPanel.add(labelTi, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 128, -1, -1));

        labelTd.setText("Td");
        this.labelTd.setVisible(false);
        parametrosPIDPanel.add(labelTd, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 161, -1, -1));

        tiTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiTextFieldKeyTyped(evt);
            }
        });
        this.tiTextField.setVisible(false);
        parametrosPIDPanel.add(tiTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 122, 78, -1));

        tdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tdTextFieldKeyTyped(evt);
            }
        });
        this.tdTextField.setVisible(false);
        parametrosPIDPanel.add(tdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 155, 78, -1));

        getContentPane().add(parametrosPIDPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 156, 210, 220));
        this.parametrosPIDPanel.setVisible(false);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 0));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel23.setText("Filtros");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        antiWindUpCheckBox.setText("Anti Windup");
        antiWindUpCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antiWindUpCheckBoxActionPerformed(evt);
            }
        });
        this.antiWindUpCheckBox.setVisible(false);
        this.antiWindUpCheckBox.setEnabled(true);
        jPanel6.add(antiWindUpCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        BotaoGerarFuncao.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        BotaoGerarFuncao.setText("OK");
        BotaoGerarFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGerarFuncaoActionPerformed(evt);
            }
        });
        jPanel6.add(BotaoGerarFuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 273, 65));

        filtroDerivativoCheckBox.setText("Filtro Derivativo");
        this.filtroDerivativoCheckBox.setVisible(false);
        jPanel6.add(filtroDerivativoCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 519, -1, 200));

        pvPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pvPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel26.setText("Variáveis de Controle");
        pvPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 2, -1, -1));

        variaveisControleGroup.add(pvTanque1);
        pvTanque1.setSelected(true);
        pvTanque1.setText("Tanque 1");
        pvTanque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvTanque1ActionPerformed(evt);
            }
        });
        pvPanel.add(pvTanque1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        variaveisControleGroup.add(pvTanque2);
        pvTanque2.setText("Tanque 2");
        pvTanque2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pvTanque2StateChanged(evt);
            }
        });
        pvPanel.add(pvTanque2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        this.pvPanel.setVisible(false);
        getContentPane().add(pvPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 379, 210, 110));

        parametrosPIDPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        parametrosPIDPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Kp");
        parametrosPIDPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 29, -1, -1));

        kpTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kpTextField1KeyTyped(evt);
            }
        });
        parametrosPIDPanel1.add(kpTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 23, 77, -1));

        labelKi1.setText("Ki");
        this.labelKi1.setVisible(false);
        parametrosPIDPanel1.add(labelKi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 62, -1, -1));

        kiTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kiTextField1KeyTyped(evt);
            }
        });
        this.kiTextField1.setVisible(false);
        parametrosPIDPanel1.add(kiTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 56, 77, -1));

        labelKd1.setText("Kd");
        this.labelKd1.setVisible(false);
        parametrosPIDPanel1.add(labelKd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 95, -1, -1));

        kdTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdTextField1ActionPerformed(evt);
            }
        });
        kdTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kdTextField1KeyTyped(evt);
            }
        });
        this.kdTextField1.setVisible(false);
        parametrosPIDPanel1.add(kdTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 89, 78, -1));

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel24.setText("Parâmetros Escravo");
        parametrosPIDPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 2, -1, -1));

        labelTi1.setText("Ti");
        this.labelTi1.setVisible(false);
        parametrosPIDPanel1.add(labelTi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 128, -1, -1));

        labelTd1.setText("Td");
        this.labelTd1.setVisible(false);
        parametrosPIDPanel1.add(labelTd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 161, -1, -1));

        tiTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiTextField1KeyTyped(evt);
            }
        });
        this.tiTextField1.setVisible(false);
        parametrosPIDPanel1.add(tiTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 122, 78, -1));

        tdTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tdTextField1KeyTyped(evt);
            }
        });
        this.tdTextField1.setVisible(false);
        parametrosPIDPanel1.add(tdTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 155, 78, -1));

        getContentPane().add(parametrosPIDPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 155, 285, 190));
        this.parametrosPIDPanel1.setVisible(false);

        jPanelEsquemaControles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelEsquemaControles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipoControleComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "P", "PI", "PD", "PID", "PI-D" }));
        tipoControleComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoControleComboBox1ActionPerformed(evt);
            }
        });
        this.tipoControleComboBox1.setVisible(false);
        jPanelEsquemaControles.add(tipoControleComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 95, 123, -1));

        jLabel25.setText("Tipo de Controle 2");
        this.jLabel25.setVisible(false);
        jPanelEsquemaControles.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 74, -1, -1));

        buttonGroup1.add(radioButtonCascata);
        radioButtonCascata.setText("Cascata");
        radioButtonCascata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCascataActionPerformed(evt);
            }
        });
        jPanelEsquemaControles.add(radioButtonCascata, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 26, -1, -1));

        buttonGroup1.add(radioButtonSimples);
        radioButtonSimples.setSelected(true);
        radioButtonSimples.setText("Simples");
        radioButtonSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSimplesActionPerformed(evt);
            }
        });
        jPanelEsquemaControles.add(radioButtonSimples, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 2, -1, -1));

        buttonGroup1.add(observadorEstadosRadio);
        observadorEstadosRadio.setText("Observador de Estados");
        observadorEstadosRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observadorEstadosRadioActionPerformed(evt);
            }
        });
        jPanelEsquemaControles.add(observadorEstadosRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 50, -1, -1));

        buttonGroup1.add(seguidorRefRadio);
        seguidorRefRadio.setText("Seguidor de Referências");
        seguidorRefRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguidorRefRadioActionPerformed(evt);
            }
        });
        jPanelEsquemaControles.add(seguidorRefRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        this.jPanelEsquemaControles.setVisible(false);
        getContentPane().add(jPanelEsquemaControles, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 28, 285, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel20.setText("Esquema de Controladores");
        this.jLabel20.setVisible(false);
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 6, -1, -1));

        obsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        obsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelObservador.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelObservador.setText("Parâmetros Observador de Estados");
        obsPanel.add(labelObservador, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 2, -1, -1));

        polosGanhosGroup.add(radioPolos);
        radioPolos.setSelected(true);
        radioPolos.setText("Polos");
        radioPolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPolosActionPerformed(evt);
            }
        });
        obsPanel.add(radioPolos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        polosGanhosGroup.add(radioGanhos);
        radioGanhos.setText("Ganhos");
        radioGanhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioGanhosActionPerformed(evt);
            }
        });
        obsPanel.add(radioGanhos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        inputPolo1.setText("0");
        obsPanel.add(inputPolo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 40, -1));

        inputPolo2.setText("0");
        inputPolo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPolo2ActionPerformed(evt);
            }
        });
        obsPanel.add(inputPolo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, -1));

        inputL0.setText("0");
        this.inputL0.setVisible(false);
        obsPanel.add(inputL0, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 77, -1));

        inputL1.setText("0");
        this.inputL1.setVisible(false);
        obsPanel.add(inputL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 77, -1));

        L0Label.setText("L0");
        obsPanel.add(L0Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, 30));

        L1Label.setText("L1");
        obsPanel.add(L1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 30));

        minusLabel.setText("+");
        obsPanel.add(minusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 20, 30));

        plusLabel.setText("+");
        obsPanel.add(plusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 20, 30));

        polo1Img.setText("0");
        polo1Img.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                polo1ImgKeyTyped(evt);
            }
        });
        obsPanel.add(polo1Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 42, -1));

        polo2Img.setText("0");
        obsPanel.add(polo2Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 42, -1));

        labelSeguidor.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        labelSeguidor.setText("Parâmetros Seguidor Referência");
        obsPanel.add(labelSeguidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        complxLabel1.setText("j");
        obsPanel.add(complxLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 50, 20, 30));

        complxLabel2.setText("j");
        obsPanel.add(complxLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 20, 30));

        polo3input.setText("0");
        obsPanel.add(polo3input, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 40, -1));

        jLabel28.setText("P1");
        obsPanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 30));

        jLabel29.setText("P2");
        obsPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabel33.setText("P3");
        obsPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, -1, 20));

        plusLabel2.setText("+");
        obsPanel.add(plusLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 30));

        polo3Img.setText("0");
        polo3Img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polo3ImgActionPerformed(evt);
            }
        });
        obsPanel.add(polo3Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 40, -1));

        complxLabel3.setText("j");
        obsPanel.add(complxLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 20, 20));

        ganhoK2input.setText("0");
        ganhoK2input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganhoK2inputActionPerformed(evt);
            }
        });
        this.ganhoK2input.setVisible(false);
        obsPanel.add(ganhoK2input, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 80, -1));

        K2Label2.setText("K2");
        obsPanel.add(K2Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 30));

        K2Label1.setText("K2");
        obsPanel.add(K2Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        K1Label.setText("K1");
        obsPanel.add(K1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        this.obsPanel.setVisible(false);
        getContentPane().add(obsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 290, 140));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 513, 960, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FuncaoSenoidalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncaoSenoidalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuncaoSenoidalActionPerformed

    private void AmplitudeMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmplitudeMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmplitudeMaximaActionPerformed

    private void PeriodoMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeriodoMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PeriodoMaximoActionPerformed

    private void BotaoGerarFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGerarFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoGerarFuncaoActionPerformed

    private void FuncaoSenoidalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoSenoidalStateChanged
        // TODO add your handling code here:
        if(this.FuncaoSenoidal.isSelected()){
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            Amplitude.setEditable(true);
            Periodo.setEditable(true);
            Offset.setVisible(true);
        }
    }//GEN-LAST:event_FuncaoSenoidalStateChanged

    private void FuncaoQuadradaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoQuadradaStateChanged
        // TODO add your handling code here:
        if(this.FuncaoQuadrada.isSelected()){
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            Amplitude.setEditable(true);
            Periodo.setEditable(true);
            Offset.setVisible(true);
        }
    }//GEN-LAST:event_FuncaoQuadradaStateChanged

    private void FuncaoDenteSerraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoDenteSerraStateChanged
        // TODO add your handling code here:
        if(this.FuncaoDenteSerra.isSelected()){
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            Amplitude.setEditable(true);
            Periodo.setEditable(true);
            Offset.setVisible(true);
        }
    }//GEN-LAST:event_FuncaoDenteSerraStateChanged

    private void FuncaoDegrauStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoDegrauStateChanged
        // TODO add your handling code here:
        if(this.FuncaoDegrau.isSelected()){
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            Amplitude.setEditable(true);
            Periodo.setEditable(false);
            Offset.setVisible(false);
        }
    }//GEN-LAST:event_FuncaoDegrauStateChanged

    private void FuncaoAleatoriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FuncaoAleatoriaStateChanged
        // TODO add your handling code here:
        if(this.FuncaoAleatoria.isSelected()){
            jPanel3.setVisible(true);
            jPanel2.setVisible(true);
            Amplitude.setEditable(false);
            Periodo.setEditable(false);
            Offset.setVisible(true);
        }
    }//GEN-LAST:event_FuncaoAleatoriaStateChanged

    private void kdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdTextFieldActionPerformed

    private void CheckMalhaFechadaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckMalhaFechadaStateChanged
        // TODO add your handling code here:
        if(this.CheckMalhaFechada.isSelected()){
            this.parametrosPIDPanel.setVisible(true);
            this.jLabel22.setVisible(true);
            this.tipoControleComboBox.setVisible(true);
            this.pvPanel.setVisible(true);
        }
    }//GEN-LAST:event_CheckMalhaFechadaStateChanged

    private void CheckMalhaAbertaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckMalhaAbertaStateChanged
        // TODO add your handling code here:
        if(this.CheckMalhaAberta.isSelected()){
            this.parametrosPIDPanel.setVisible(false);
            this.jLabel22.setVisible(false);
            this.tipoControleComboBox.setVisible(false);
            this.pvPanel.setVisible(false);
            this.obsPanel.setVisible(false);
            this.jPanelEsquemaControles.setVisible(false);
            this.parametrosPIDPanel1.setVisible(false);
        }
    }//GEN-LAST:event_CheckMalhaAbertaStateChanged

    public boolean isAntiWindUpActive(){
        return this.antiWindUpCheckBox.isSelected();
    }
    
    private void tipoControleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoControleComboBoxActionPerformed
        int tipoControle = this.tipoControleComboBox.getSelectedIndex();
        
        if(tipoControle == 0){//tipo P
            this.labelKi.setVisible(false);
            this.labelTi.setVisible(false);
            this.labelKd.setVisible(false);
            this.labelTd.setVisible(false);
            
            this.kpTextField.setVisible(true);
            this.kiTextField.setVisible(false);
            this.kdTextField.setVisible(false);
            
            this.tiTextField.setVisible(false);
            this.tdTextField.setVisible(false);
            this.antiWindUpCheckBox.setVisible(false);
            this.antiWindUpCheckBox.setSelected(false);
            this.filtroDerivativoCheckBox.setVisible(false);
            this.filtroDerivativoCheckBox.setSelected(false);
        }
        else if(tipoControle == 1){//tipo PI
            this.labelKi.setVisible(true);
            this.labelTi.setVisible(true);
            this.labelKd.setVisible(false);
            this.labelTd.setVisible(false);
            
            this.kpTextField.setVisible(true);
            this.kiTextField.setVisible(true);
            this.kdTextField.setVisible(false);
            
            this.tiTextField.setVisible(true);
            this.tdTextField.setVisible(false);
            
            //filtros
            this.antiWindUpCheckBox.setVisible(true);
            this.filtroDerivativoCheckBox.setVisible(false);
            this.filtroDerivativoCheckBox.setSelected(false);
        }
        else if(tipoControle == 2){//tipo PD
            this.labelKi.setVisible(false);
            this.labelTi.setVisible(false);
            this.labelKd.setVisible(true);
            this.labelTd.setVisible(true);
            
            this.kpTextField.setVisible(true);
            this.kiTextField.setVisible(false);
            this.kdTextField.setVisible(true);
            
            this.tiTextField.setVisible(false);
            this.tdTextField.setVisible(true);
            
            //filtros
            this.antiWindUpCheckBox.setVisible(false);
            this.antiWindUpCheckBox.setSelected(false);
            this.filtroDerivativoCheckBox.setVisible(true);
        }
        else if(tipoControle == 3){//tipo PID
            this.labelKi.setVisible(true);
            this.labelTi.setVisible(true);
            this.labelKd.setVisible(true);
            this.labelTd.setVisible(true);
            
            this.kpTextField.setVisible(true);
            this.kiTextField.setVisible(true);
            this.kdTextField.setVisible(true);
            
            this.tiTextField.setVisible(true);
            this.tdTextField.setVisible(true);
            
            //filtros
            this.antiWindUpCheckBox.setVisible(true);
            this.filtroDerivativoCheckBox.setVisible(true);
        }
        else if(tipoControle == 4){//tipo PI-D
            this.labelKi.setVisible(true);
            this.labelTi.setVisible(true);
            this.labelKd.setVisible(true);
            this.labelTd.setVisible(true);
            
            this.kpTextField.setVisible(true);
            this.kiTextField.setVisible(true);
            this.kdTextField.setVisible(true);
            
            this.tiTextField.setVisible(true);
            this.tdTextField.setVisible(true);
            
            //filtros
            this.antiWindUpCheckBox.setVisible(true);
            this.filtroDerivativoCheckBox.setVisible(true);
        }
    }//GEN-LAST:event_tipoControleComboBoxActionPerformed

    private void kpTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kpTextFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_kpTextFieldKeyTyped

    private void kiTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kiTextFieldKeyTyped
        // TODO add your handling code here:
        this.tiTextField.setText("NaN");
    }//GEN-LAST:event_kiTextFieldKeyTyped

    private void kdTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kdTextFieldKeyTyped
        // TODO add your handling code here:
        this.tdTextField.setText("NaN");
    }//GEN-LAST:event_kdTextFieldKeyTyped

    private void tiTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiTextFieldKeyTyped
        // TODO add your handling code here:
        this.kiTextField.setText("NaN");
    }//GEN-LAST:event_tiTextFieldKeyTyped

    private void tdTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdTextFieldKeyTyped
        // TODO add your handling code here:
        this.kdTextField.setText("NaN");
    }//GEN-LAST:event_tdTextFieldKeyTyped

    private void antiWindUpCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antiWindUpCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antiWindUpCheckBoxActionPerformed

    private void pvTanque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvTanque1ActionPerformed
        if(this.pvTanque1.isSelected()){
            this.parametrosPIDPanel1.setVisible(false);
        }
    }//GEN-LAST:event_pvTanque1ActionPerformed

    private void kpTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kpTextField1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_kpTextField1KeyTyped

    private void kiTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kiTextField1KeyTyped
        this.tiTextField1.setText("NaN");
    }//GEN-LAST:event_kiTextField1KeyTyped

    private void kdTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdTextField1ActionPerformed

    private void kdTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kdTextField1KeyTyped
        this.tdTextField1.setText("NaN");
    }//GEN-LAST:event_kdTextField1KeyTyped

    private void tiTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiTextField1KeyTyped
        this.kiTextField1.setText("NaN");
    }//GEN-LAST:event_tiTextField1KeyTyped

    private void tdTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdTextField1KeyTyped
        this.kdTextField1.setText("NaN");
    }//GEN-LAST:event_tdTextField1KeyTyped

    private void tipoControleComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoControleComboBox1ActionPerformed

        int tipoControle = this.tipoControleComboBox1.getSelectedIndex();
        
        if(tipoControle == 0){//tipo P
            this.labelKi1.setVisible(false);
            this.labelTi1.setVisible(false);
            this.labelKd1.setVisible(false);
            this.labelTd1.setVisible(false);
            
            this.kpTextField1.setVisible(true);
            this.kiTextField1.setVisible(false);
            this.kdTextField1.setVisible(false);
            
            this.tiTextField1.setVisible(false);
            this.tdTextField1.setVisible(false);
        }
        else if(tipoControle == 1){//tipo PI
            this.labelKi1.setVisible(true);
            this.labelTi1.setVisible(true);
            this.labelKd1.setVisible(false);
            this.labelTd1.setVisible(false);
            
            this.kpTextField1.setVisible(true);
            this.kiTextField1.setVisible(true);
            this.kdTextField1.setVisible(false);
            
            this.tiTextField1.setVisible(true);
            this.tdTextField1.setVisible(false);
            
        }
        else if(tipoControle == 2){//tipo PD
            this.labelKi1.setVisible(false);
            this.labelTi1.setVisible(false);
            this.labelKd1.setVisible(true);
            this.labelTd1.setVisible(true);
            
            this.kpTextField1.setVisible(true);
            this.kiTextField1.setVisible(false);
            this.kdTextField1.setVisible(true);
            
            this.tiTextField1.setVisible(false);
            this.tdTextField1.setVisible(true);
            
        }
        else if(tipoControle == 3){//tipo PID
            this.labelKi1.setVisible(true);
            this.labelTi1.setVisible(true);
            this.labelKd1.setVisible(true);
            this.labelTd1.setVisible(true);
            
            this.kpTextField1.setVisible(true);
            this.kiTextField1.setVisible(true);
            this.kdTextField1.setVisible(true);
            
            this.tiTextField1.setVisible(true);
            this.tdTextField1.setVisible(true);
                      
        }
        else if(tipoControle == 4){//tipo PI-D
            this.labelKi1.setVisible(true);
            this.labelTi1.setVisible(true);
            this.labelKd1.setVisible(true);
            this.labelTd1.setVisible(true);
            
            this.kpTextField1.setVisible(true);
            this.kiTextField1.setVisible(true);
            this.kdTextField1.setVisible(true);
            
            this.tiTextField1.setVisible(true);
            this.tdTextField1.setVisible(true);
            
        }
    }//GEN-LAST:event_tipoControleComboBox1ActionPerformed

    private void pvTanque2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pvTanque2StateChanged
        if(this.pvTanque2.isSelected()){
            this.jPanelEsquemaControles.setVisible(true);
            this.jLabel20.setVisible(true);
        }
        else{
            this.jPanelEsquemaControles.setVisible(false);
            this.jLabel20.setVisible(false);
            this.obsPanel.setVisible(false);
        }
    }//GEN-LAST:event_pvTanque2StateChanged

    private void radioButtonCascataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCascataActionPerformed
        if(this.radioButtonCascata.isSelected()){
            this.parametrosPIDPanel1.setVisible(true);
            this.tipoControleComboBox1.setVisible(true);
            this.jLabel25.setVisible(true);
            this.obsPanel.setVisible(false);
        }
    }//GEN-LAST:event_radioButtonCascataActionPerformed

    private void radioButtonSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSimplesActionPerformed
        if(this.radioButtonSimples.isSelected()){
            this.parametrosPIDPanel1.setVisible(false);
            this.tipoControleComboBox1.setVisible(false);
            this.jLabel25.setVisible(false);
            this.obsPanel.setVisible(false);
        }
    }//GEN-LAST:event_radioButtonSimplesActionPerformed
    
    private void radioPolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPolosActionPerformed
        if(this.radioPolos.isSelected()){
            this.inputL0.setVisible(false);
            this.inputL1.setVisible(false);
            this.inputPolo1.setVisible(true);
            this.inputPolo2.setVisible(true);
            this.polo3input.setVisible(true);
            this.polo1Img.setVisible(true);
            this.polo2Img.setVisible(true);
            this.polo3Img.setVisible(true);
            this.plusLabel.setVisible(true);
            this.plusLabel2.setVisible(true);
            this.minusLabel.setVisible(true);
            this.complxLabel1.setVisible(true);
            this.complxLabel2.setVisible(true);
            this.complxLabel3.setVisible(true);
            this.ganhoK2input.setVisible(false);
        }
    }//GEN-LAST:event_radioPolosActionPerformed

    private void radioGanhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioGanhosActionPerformed
        if(this.radioGanhos.isSelected()){
            this.inputL0.setVisible(true);
            this.inputL1.setVisible(true);
            this.inputPolo1.setVisible(false);
            this.inputPolo2.setVisible(false);
            this.polo3input.setVisible(false);
            this.polo1Img.setVisible(false);
            this.polo2Img.setVisible(false);
            this.polo3Img.setVisible(false);
            this.plusLabel.setVisible(false);
            this.plusLabel2.setVisible(false);
            this.minusLabel.setVisible(false);
            this.complxLabel1.setVisible(false);
            this.complxLabel2.setVisible(false);
            this.complxLabel3.setVisible(false);
            if(this.seguidorRefRadio.isSelected())
                this.ganhoK2input.setVisible(true);
        }
    }//GEN-LAST:event_radioGanhosActionPerformed

    private void observadorEstadosRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observadorEstadosRadioActionPerformed
        if(this.observadorEstadosRadio.isSelected()){
            this.parametrosPIDPanel1.setVisible(false);
            this.tipoControleComboBox1.setVisible(false);
            this.jLabel25.setVisible(false);
            this.obsPanel.setVisible(true);
            this.labelObservador.setVisible(true);
            this.labelSeguidor.setVisible(false);
            this.K1Label.setVisible(false);
            this.K2Label1.setVisible(false);
            this.K2Label2.setVisible(false);
            this.L0Label.setVisible(true);
            this.L1Label.setVisible(true);
            this.ganhoK2input.setVisible(false);
        }
    }//GEN-LAST:event_observadorEstadosRadioActionPerformed

    private void seguidorRefRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguidorRefRadioActionPerformed
        if(this.seguidorRefRadio.isSelected()){
            this.parametrosPIDPanel1.setVisible(false);
            this.tipoControleComboBox1.setVisible(false);
            this.jLabel25.setVisible(false);
            this.obsPanel.setVisible(true);
            this.labelObservador.setVisible(false);
            this.labelSeguidor.setVisible(true);
            this.K1Label.setVisible(true);
            this.K2Label1.setVisible(true);
            this.K2Label2.setVisible(true);
            this.L0Label.setVisible(false);
            this.L1Label.setVisible(false);
        }
    }//GEN-LAST:event_seguidorRefRadioActionPerformed

    private void polo1ImgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_polo1ImgKeyTyped

    }//GEN-LAST:event_polo1ImgKeyTyped

    private void polo3ImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polo3ImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_polo3ImgActionPerformed

    private void inputPolo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPolo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPolo2ActionPerformed

    private void ganhoK2inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganhoK2inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ganhoK2inputActionPerformed
    
    public float getImg(){
        return Float.parseFloat(this.polo1Img.getText());
    }
    
    public String getKpValor(){
        return kpTextField.getText();
    }
    
    public String getKiValor(){
        return kiTextField.getText();
    }
    
    public String getKdValor(){
        return kdTextField.getText();
    }
    
    public String getTiValor(){
        return tiTextField.getText();
    }
    
    public String getTdValor(){
        return tdTextField.getText();
    }
    
    public String getKp1Valor(){
        return kpTextField1.getText();
    }
    
    public String getKi1Valor(){
        return kiTextField1.getText();
    }
    
    public String getKd1Valor(){
        return kdTextField1.getText();
    }
    
    public String getTi1Valor(){
        return tiTextField1.getText();
    }
    
    public String getTd1Valor(){
        return tdTextField1.getText();
    }
    
    public int getSelectedControle(){
        return this.tipoControleComboBox.getSelectedIndex();
    }
    
    public int getSelectedControle1(){
        return this.tipoControleComboBox1.getSelectedIndex();
    }
    
    public String GetFuncaoSelecionada(){
        String funcao;
        if (FuncaoSenoidal.isSelected()) funcao = "senoidal";
        else if (FuncaoQuadrada.isSelected()) funcao = "quadrada";
        else if (FuncaoDegrau.isSelected()) funcao = "degrau";
        else if (FuncaoDenteSerra.isSelected()) funcao = "serra";
        else if (FuncaoAleatoria.isSelected()) funcao = "aleatoria";
        else funcao = "erro";
        return funcao;
    }
    public double GetAmplitude(){
        return Double.parseDouble(Amplitude.getText());
    }
    public double GetPeriodo(){
        return Double.parseDouble(Periodo.getText());
    }
    public double GetOffset(){
        double offset = 0;
        try{
            offset = Double.parseDouble(Offset.getText());
        } catch (Exception e ){
            if(this.isMalhaFechada()){
                theresError = true;
                erro += "Offset inválido\n";
            }
        }
        return offset;
    }
    public double GetAmplitudeMinima(){
        return Double.parseDouble(AmplitudeMinima.getText());
    }
    public double GetAmplitudeMaxima(){
        return Double.parseDouble(AmplitudeMaxima.getText());
    }
    public double GetPeridoMinimo(){
        return Double.parseDouble(PeriodoMinimo.getText());
    }
    public double GetPeriodoMaximo(){
        return Double.parseDouble(PeriodoMaximo.getText());
    }
    public boolean isMalhaFechada(){
        return CheckMalhaFechada.isSelected();
    }
    public void mostrarErro(){
        JOptionPane.showMessageDialog(null, this.erro, "Erro!", JOptionPane.ERROR_MESSAGE);
    } 
    public void addGerarFuncaoListener(ActionListener listen){
        BotaoGerarFuncao.addActionListener(listen);
    }
    
    public double[] getPIDValores(){
        theresError = false;
        double p = 0, i = 0, d = 0;
        
        double[] param = new double[3];
        try{
            p = Double.parseDouble(this.getKpValor());
        } catch (Exception e) {
            theresError = true;
            erro += "Valor de Kp inválido.\n";
        }
        
        if(this.getKiValor().isEmpty() && this.getTiValor().isEmpty()){
            i = 0;
        }
        else{
            if("NaN".equals(this.getKiValor())){
                try{
                    i = Double.parseDouble(this.getTiValor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Ti inválido.\n";
                }
            }
            else{
                try{
                    i = Double.parseDouble(this.getKiValor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Ki inválido.\n";
                }
            }
        }
        
        if(this.getKdValor().isEmpty() && this.getTdValor().isEmpty()){
            d = 0;
        }
        else{
            if("NaN".equals(this.getKdValor())){
                try{
                    d = Double.parseDouble(this.getTdValor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Td inválido.\n";
                }
            }
            else{
                try{
                    i = Double.parseDouble(this.getKdValor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Kd inválido.\n";
                }
            }
        }
        
        param[0] = p;
        param[1] = i;
        param[2] = d;
        
        return param;
    }
    
    public boolean isKi(){
        if(this.getKiValor().isEmpty() && this.getTiValor().isEmpty()){
            return false;
        }
        else{
            return !"NaN".equals(this.getKiValor());
        }
    }
    
    public boolean isKd(){
        if(this.getKdValor().isEmpty() && this.getTdValor().isEmpty()){
            return false;
        }
        else{
            return !"NaN".equals(this.getKdValor());
        }
    }
    
    public int getPV(){
        if(this.pvTanque1.isSelected()){
            return 0;
        }
        else if(this.pvTanque2.isSelected()){
            return 1;
        }
        else{
            return -1;
        }
    }
    
    public boolean isDerivativoAtivado(){
        return this.filtroDerivativoCheckBox.isSelected();
    }
    
    public boolean isCascata(){
        return this.radioButtonCascata.isSelected();
    }
    
    public double[] getPID2Valores(){
        
        theresError = false;
        double p = 0, i = 0, d = 0;
        
        double[] param = new double[3];
        try{
            p = Double.parseDouble(this.getKp1Valor());
        } catch (Exception e) {
            theresError = true;
            erro += "Valor de Kp inválido.\n";
        }
        
        if(this.getKi1Valor().isEmpty() && this.getTi1Valor().isEmpty()){
            i = 0;
        }
        else{
            if("NaN".equals(this.getKi1Valor())){
                try{
                    i = Double.parseDouble(this.getTi1Valor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Ti inválido.\n";
                }
            }
            else{
                try{
                    i = Double.parseDouble(this.getKi1Valor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Ki inválido.\n";
                }
            }
        }
        
        if(this.getKd1Valor().isEmpty() && this.getTd1Valor().isEmpty()){
            d = 0;
        }
        else{
            if("NaN".equals(this.getKdValor())){
                try{
                    d = Double.parseDouble(this.getTd1Valor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Td inválido.\n";
                }
            }
            else{
                try{
                    i = Double.parseDouble(this.getKd1Valor());
                } catch (Exception e) {
                    theresError = true;
                    erro += "Valor de Kd inválido.\n";
                }
            }
        }
        
        param[0] = p;
        param[1] = i;
        param[2] = d;
        
        return param;
    }
    
    public boolean isKi1(){
        if(this.getKi1Valor().isEmpty() && this.getTi1Valor().isEmpty()){
            return false;
        }
        else{
            return !"NaN".equals(this.getKi1Valor());
        }
    }
    public boolean estadoCascata(){
        return this.radioButtonCascata.isSelected();
    }
    public boolean isKd1(){
        if(this.getKd1Valor().isEmpty() && this.getTd1Valor().isEmpty()){
            return false;
        }
        else{
            return !"NaN".equals(this.getKd1Valor());
        }
    }
    
    public boolean isObsEstados(){
        return this.observadorEstadosRadio.isSelected();
    }
    
    public float[] getPolos(){
        float polos[] = new float[2];
        polos[0] = Float.parseFloat(this.inputPolo1.getText());
        polos[1] = Float.parseFloat(this.inputPolo2.getText());
        
        return polos;
    }
    
    public float[] getGanhos(){
        float ganhos[] = new float[2];
        ganhos[0] = Float.parseFloat(this.inputL0.getText());
        ganhos[1] = Float.parseFloat(this.inputL1.getText());
        
        return ganhos;
    }
    
    public boolean isPolos(){
        return this.radioPolos.isSelected();
    }
    
    public boolean isGanhos(){
        return this.radioGanhos.isSelected();
    }
    
    public void setL0(double l0){
        this.inputL0.setText(""+l0);
    }
    
    public void setL1(double l1){
        this.inputL1.setText(""+l1);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Amplitude;
    public javax.swing.JTextField AmplitudeMaxima;
    public javax.swing.JTextField AmplitudeMinima;
    public javax.swing.JButton BotaoGerarFuncao;
    public javax.swing.JRadioButton CheckMalhaAberta;
    public javax.swing.JRadioButton CheckMalhaFechada;
    public javax.swing.JRadioButton FuncaoAleatoria;
    public javax.swing.JRadioButton FuncaoDegrau;
    public javax.swing.JRadioButton FuncaoDenteSerra;
    public javax.swing.JRadioButton FuncaoQuadrada;
    public javax.swing.JRadioButton FuncaoSenoidal;
    public javax.swing.JLabel K1Label;
    public javax.swing.JLabel K2Label1;
    public javax.swing.JLabel K2Label2;
    public javax.swing.JLabel L0Label;
    public javax.swing.JLabel L1Label;
    public javax.swing.JTextField Offset;
    public javax.swing.JTextField Periodo;
    public javax.swing.JTextField PeriodoMaximo;
    public javax.swing.JTextField PeriodoMinimo;
    public javax.swing.ButtonGroup TipoFuncao;
    public javax.swing.JCheckBox antiWindUpCheckBox;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.ButtonGroup buttonGroup3;
    public javax.swing.JLabel complxLabel1;
    public javax.swing.JLabel complxLabel2;
    public javax.swing.JLabel complxLabel3;
    public javax.swing.JCheckBox filtroDerivativoCheckBox;
    public javax.swing.JTextField ganhoK2input;
    public javax.swing.JTextField inputL0;
    public javax.swing.JTextField inputL1;
    public javax.swing.JTextField inputPolo1;
    public javax.swing.JTextField inputPolo2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanelEsquemaControles;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField kdTextField;
    public javax.swing.JTextField kdTextField1;
    public javax.swing.JTextField kiTextField;
    public javax.swing.JTextField kiTextField1;
    public javax.swing.JTextField kpTextField;
    public javax.swing.JTextField kpTextField1;
    public javax.swing.JLabel labelKd;
    public javax.swing.JLabel labelKd1;
    public javax.swing.JLabel labelKi;
    public javax.swing.JLabel labelKi1;
    public javax.swing.JLabel labelObservador;
    public javax.swing.JLabel labelSeguidor;
    public javax.swing.JLabel labelTd;
    public javax.swing.JLabel labelTd1;
    public javax.swing.JLabel labelTi;
    public javax.swing.JLabel labelTi1;
    public javax.swing.JLabel minusLabel;
    public javax.swing.JPanel obsPanel;
    public javax.swing.JRadioButton observadorEstadosRadio;
    public javax.swing.JPanel parametrosPIDPanel;
    public javax.swing.JPanel parametrosPIDPanel1;
    public javax.swing.JLabel plusLabel;
    public javax.swing.JLabel plusLabel2;
    public javax.swing.JTextField polo1Img;
    public javax.swing.JTextField polo2Img;
    public javax.swing.JTextField polo3Img;
    public javax.swing.JTextField polo3input;
    public javax.swing.ButtonGroup polosGanhosGroup;
    public javax.swing.JPanel pvPanel;
    public javax.swing.JRadioButton pvTanque1;
    public javax.swing.JRadioButton pvTanque2;
    public javax.swing.JRadioButton radioButtonCascata;
    public javax.swing.JRadioButton radioButtonSimples;
    public javax.swing.JRadioButton radioGanhos;
    public javax.swing.JRadioButton radioPolos;
    public javax.swing.JRadioButton seguidorRefRadio;
    public javax.swing.JTextField tdTextField;
    public javax.swing.JTextField tdTextField1;
    public javax.swing.JTextField tiTextField;
    public javax.swing.JTextField tiTextField1;
    public javax.swing.JComboBox<String> tipoControleComboBox;
    public javax.swing.JComboBox<String> tipoControleComboBox1;
    public javax.swing.ButtonGroup tipoMalha;
    public javax.swing.ButtonGroup variaveisControleGroup;
    // End of variables declaration//GEN-END:variables
}
